# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Work around a broken path in RNFBAnalytics.podspec published in some versions.
rnfb_analytics_podspec = File.join(__dir__, '..', 'node_modules', '@react-native-firebase', 'analytics', 'RNFBAnalytics.podspec')
if File.exist?(rnfb_analytics_podspec)
  podspec_content = File.read(rnfb_analytics_podspec)
  bad_path = "File.join('..', 'app', 'package.json')"
  fixed_path = "File.join(__dir__, '..', 'app', 'package.json')"
  if podspec_content.include?(bad_path)
    Pod::UI.puts 'Patching RNFBAnalytics.podspec path bug'
    File.write(rnfb_analytics_podspec, podspec_content.gsub(bad_path, fixed_path))
  end
end

target 'ExampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
